/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budget;

import java.awt.Color;
import java.text.NumberFormat;
import Calculate.Calculations;
import java.awt.Graphics;
import javax.swing.JPanel;
import javax.swing.UIManager;
/**
 *
 * @author Trenton Thompson
 */
public class BudgetFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form BudgetFrame
     */
    public BudgetFrame() {
        initComponents();
    getContentPane().setBackground(Color.cyan);

    } /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budget = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        utilities = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        groceries = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fuel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entertainment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        carPayment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        carInsurance = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        misc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cable = new javax.swing.JTextField();
        internet = new javax.swing.JTextField();
        dining = new javax.swing.JTextField();
        savings = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        investments = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        supplies = new javax.swing.JTextField();
        clothing = new javax.swing.JTextField();
        personal = new javax.swing.JTextField();
        creditCard = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        budget.setEditable(false);
        budget.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        budget.setToolTipText("This is your budget based on your total allocations.");
        budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("Monthly Budget");

        rent.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        rent.setToolTipText("Enter your Monthly Mortgage or Rent.");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Mortgage/Rent:");

        utilities.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        utilities.setToolTipText("Enter Water/Sewer/Gas/Electric expense total here.");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("Utilities:");

        groceries.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        groceries.setToolTipText("Enter your Total Groceries Allocation.");

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("Groceries:");

        fuel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        fuel.setToolTipText("Enter your total Gas Allocation.");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setText("Fuel/Gas:");

        entertainment.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        entertainment.setToolTipText("Enter your total fun expenses.");

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setText("Entertainment:");

        carPayment.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        carPayment.setToolTipText("Enter monthly auto payment.");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("Auto Loan:");

        carInsurance.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        carInsurance.setToolTipText("Enter your vehicles monthly insurance.");

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("Auto Ins:");

        misc.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        misc.setToolTipText("Enter total monthly amount for Misc. Expenses.");

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("Miscellaneous:");

        phone.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        phone.setToolTipText("Enter your phone payment.");

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel10.setText("Phone:");

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel11.setText("Cable");

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel12.setText("Internet:");

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setText("Credit Cards:");

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel14.setText("Dining:");

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel15.setText("Savings:");

        cable.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        cable.setToolTipText("Enter your Cable or Satellite payment.");

        internet.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        internet.setToolTipText("Enter Internet payment.");

        dining.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dining.setToolTipText("Enter total Dining out expenses.");

        savings.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        savings.setToolTipText("Enter Savings allocation payment.");

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel16.setText("Investments:");

        investments.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        investments.setToolTipText("Enter your total monthly investment.");

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel17.setText("Supplies:");

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel18.setText("Clothing:");

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel19.setText("Personal:");

        supplies.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        supplies.setToolTipText("Enter total monthly supplies.");

        clothing.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        clothing.setToolTipText("Enter total monthly clothing expenses.");

        personal.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        personal.setToolTipText("Enter total monthly personal expenses.");

        creditCard.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        creditCard.setToolTipText("Enter total Credit Card payment.");

        calculate.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(utilities, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groceries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entertainment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(misc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cable, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(internet, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(investments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculate)
                    .addComponent(exit))
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(budget, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel20)))
                .addContainerGap(757, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cable, clothing, creditCard, dining, internet, investments, jLabel1, jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, personal, savings, supplies});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {carInsurance, carPayment, entertainment, fuel, groceries, misc, phone, rent, utilities});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {calculate, exit, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(internet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groceries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(creditCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(dining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(entertainment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(savings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(investments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(carPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(carInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(supplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(misc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(clothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addComponent(jLabel20)
                .addGap(28, 28, 28))
        );

        jLabel20.getAccessibleContext().setAccessibleName("jLabel13");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void budgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgetActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
       if (isValidData()){
        double r = Double.parseDouble(rent.getText());
        double u = Double.parseDouble(utilities.getText());
        double g = Double.parseDouble(groceries.getText());
        double f = Double.parseDouble(fuel.getText());
        double e = Double.parseDouble(entertainment.getText());
        double cp = Double.parseDouble(carPayment.getText());
        double ci = Double.parseDouble(carInsurance.getText());
        double m = Double.parseDouble(misc.getText());
        double p = Double.parseDouble(phone.getText());
        double c = Double.parseDouble(cable.getText());
        double i = Double.parseDouble(internet.getText());
        double cc = Double.parseDouble(creditCard.getText());
        double d = Double.parseDouble(dining.getText());
        double s = Double.parseDouble(savings.getText());
        double inv = Double.parseDouble(investments.getText());
        double sup = Double.parseDouble(supplies.getText());
        double cloth = Double.parseDouble(clothing.getText());
        double pers = Double.parseDouble(personal.getText());
        double Budget = Calculations.calculateBudget(r, u, g, f, e, cp, ci, m, p, c, cc, i, d, s, inv, sup, cloth, pers);
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        budget.setText(currency.format(Budget));// TODO add your handling code here:
       }
    }//GEN-LAST:event_calculateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
          System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

     private boolean isValidData()
    {
        BudgetValidator bv = new BudgetValidator();
        return
            bv.isPresent(rent, "Mortgage/Rent") &&
            bv.isDouble(rent, "Mortgage/Rent") &&
            bv.isPresent(utilities, "Utilities") &&
            bv.isDouble(utilities, "Utilities") &&
            bv.isPresent(groceries, "Groceries") &&
            bv.isDouble(groceries, "Groceries") &&
            bv.isPresent(fuel, "Fuel/Gas") &&
            bv.isDouble(fuel, "Fuel/Gas") &&
            bv.isPresent(entertainment, "Entertainment") &&
            bv.isDouble(entertainment, "Entertainment") &&
            bv.isPresent(carPayment, "Auto Loan") &&
            bv.isDouble(carPayment, "Auto Loan") &&
            bv.isPresent(carInsurance, "Auto Insurance") &&
            bv.isDouble(carInsurance, "Auto Insurance") &&
            bv.isPresent(misc, "Miscellaneous") &&
            bv.isDouble(misc, "Miscellaneous") &&
            bv.isPresent(phone, "Phone") &&
            bv.isDouble(phone, "Phone") &&
            bv.isPresent(cable, "Cable/Satellite") &&
            bv.isDouble(cable, "Cable/Satellite") &&
            bv.isPresent(internet, "Internet") &&
            bv.isDouble(internet, "Internet") &&
            bv.isPresent(creditCard, "Credit Card") &&
            bv.isDouble(creditCard, "Credit Card") && 
            bv.isPresent(dining, "Dining") &&
            bv.isDouble(dining, "Dining") &&
            bv.isPresent(savings, "Savings") &&
            bv.isDouble(savings, "Savings") &&
            bv.isPresent(investments, "Investments") &&
            bv.isDouble(investments, "Investments") &&
            bv.isPresent(supplies, "Supplies") &&
            bv.isDouble(supplies, "Supplies") &&
            bv.isPresent(clothing, "Clothing") &&
            bv.isDouble(clothing, "Clothing") &&
            bv.isPresent(personal, "Personal") &&
            bv.isDouble(personal, "Personal");
            
    }
    
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } else {
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BudgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BudgetFrame().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budget;
    private javax.swing.JTextField cable;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField carInsurance;
    private javax.swing.JTextField carPayment;
    private javax.swing.JTextField clothing;
    private javax.swing.JTextField creditCard;
    private javax.swing.JTextField dining;
    private javax.swing.JTextField entertainment;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fuel;
    private javax.swing.JTextField groceries;
    private javax.swing.JTextField internet;
    private javax.swing.JTextField investments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField misc;
    private javax.swing.JTextField personal;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField rent;
    private javax.swing.JTextField savings;
    private javax.swing.JTextField supplies;
    private javax.swing.JTextField utilities;
    // End of variables declaration//GEN-END:variables
}
